run:
  timeout: 2m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - deadcode
    - typecheck
    - varcheck
    - ineffassign
    - gofmt
    - goimports
    - misspell 